spring:
  application:
    name: product

  datasource:
    url: jdbc:postgresql://${PRODUCT_DB_URL}
    username: ${PRODUCT_DB_USERNAME}
    password: ${PRODUCT_DB_PASSWORD}

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#  h2:
#    console:
#      enabled: true
#
#    datasource:
#      url: jdbc:h2:mem:product
#
#    jpa:
#      show-sql: true
#      hibernate:
#        ddl-auto: create

server:
  port: ${PRODUCT_PORT}