spring:
  application:
    name: order
  datasource:
    url: jdbc:postgresql://${ORDER_DB_URL}
    username: ${ORDER_DB_USERNAME}
    password: ${ORDER_DB_PASSWORD}
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

product:
  service:
    url: http://localhost:8083/api/product
user:
  service:
    url: http://localhost:8082/api/users

server:
  port: ${ORDER_PORT}